### ISSUE TITLE
Web dev 2- 030- Am I forgetting something?

### ISSUE THREAD

**Issue by ShaylynHM** [ShaylynHM/euro-just-doing-semantics#1]
@thatkidmadrid
@wendywarren 
Help SOS

![Screen Shot 2021-09-17 at 8 07 15 PM](https://user-images.githubusercontent.com/77545465/133865225-75e74f12-1618-44ac-ab1c-0f69ecef6446.png)

<img width="1063" alt="Screen Shot 2021-09-17 at 8 07 26 PM" src="https://user-images.githubusercontent.com/77545465/133865227-0bd5ae5d-8c0a-4d90-aa57-3b22be9efdd5.png">

**Comment by thatkidmadrid** [comment]
Hey Shaylyn,

It looks like you're missing the closing character `>` after you set your `charset` to `utf-8` on **line 4**

instead of
```
<meta charset="utf-8">
```
it is written as
```
<meta charset="utf-8"
```
This would throw off the validation of your html file as the browser thinks the closing carat `>` for the `meta` tag  is the one that actually closes your opening `title` tag. 

Give that a shot and please let me know if that fixes things

## hint
Pay close attention to the colour-codiung in your text editor. If things look a bit off, the colour-coding can often give hints for missing closing characters or tags. Look for where the colour-coding stops making sense and that is often where the culprit lies.
